name: Java CI with Gradle

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: make application-nas.yml
        run: |
          touch ./src/main/resources/application-nas.yml
          echo "${{secrets.APPLICATION }}" > ./src/main/resources/application-nas.yml

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build

      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/cafe_user .
          docker push ${{ secrets.DOCKER_REPO }}/cafe_user

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAS_HOST }}
          port: ${{ secrets.NAS_PORT }}
          username: ${{ secrets.NAS_USERNAME }}
          password: ${{ secrets.NAS_PASSWORD }}
          script: |
            export PATH=${{ secrets.SHELL_PATH }}
            docker rm -f cafe_user
            docker pull ${{ secrets.DOCKER_REPO }}/cafe_user
            docker run -d --name cafe_cafe --restart=unless-stopped -p 8091:8080 ${{ secrets.DOCKER_REPO }}/cafe_user:latest